### ISSUE TITLE
error

### ISSUE THREAD

**Issue by david141** [Hazel1994/ViPE-Videos#1]
$ python generate_video.py --mp3_file story --saving_dir ./rabbit_story/
D:\soft\Python\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed
 to load image Python extension: '[WinError 127] Не найдена указанная процедура'
If you don't plan on using image functionality from `torchvision.io`, you can ig
nore this warning. Otherwise, there might be something wrong with your environme
nt. Did you have `libjpeg` or `libpng` installed before building `torchvision` f
rom source?
  warn(
Traceback (most recent call last):
  File "D:\AI\ViPE-Videos\generate_video.py", line 11, in <module>
    from ViPE.utils import dotdict, get_lyrtic2prompts, get_track_intensity, get
_visual_effects, get_visual_effects_disco
  File "D:\AI\ViPE-Videos\ViPE\utils.py", line 1, in <module>
    import whisper
  File "C:\Users\david\AppData\Roaming\Python\Python310\site-packages\whisper.py
", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "D:\soft\Python\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by david141** [comment]
$ python generate_video.py --mp3_file story --saving_dir rabbit_story
Traceback (most recent call last):
  File "D:\AI\ViPE-Videos\generate_video.py", line 11, in <module>
    from ViPE.utils import dotdict, get_lyrtic2prompts, get_track_intensity, get
_visual_effects, get_visual_effects_disco
  File "D:\AI\ViPE-Videos\ViPE\utils.py", line 1, in <module>
    import whisper
  File "C:\Users\david\AppData\Roaming\Python\Python310\site-packages\whisper.py
", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "D:\soft\Python\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by david141** [comment]
Please check the timestamps of the generated transcription.
Enter 'yes' to continue if youre happy with the transcription, or 'no' to stop a
nd manually correct the file.): yes
Continuing to generate video...
config.json: 100%|█████████████████████████████| 967/967 [00:00<00:00, 966kB/s]
pytorch_model.bin: 100%|██████████████████| 1.44G/1.44G [02:05<00:00, 11.6MB/s]
vocab.json: 100%|█████████████████████████| 1.04M/1.04M [00:00<00:00, 2.45MB/s]
merges.txt: 100%|███████████████████████████| 456k/456k [00:00<00:00, 1.46MB/s]
tokenizer_config.json: 100%|████████████████████████| 26.0/26.0 [00:00<?, ?B/s]
config.json: 100%|████████████████████████████████████| 718/718 [00:00<?, ?B/s]
config.json: 100%|████████████████████████████████████| 587/587 [00:00<?, ?B/s]
pytorch_model.bin: 100%|████████████████████| 438M/438M [00:37<00:00, 11.6MB/s]
tokenizer_config.json: 100%|██████████████| 1.19k/1.19k [00:00<00:00, 1.18MB/s]
vocab.txt: 100%|████████████████████████████| 232k/232k [00:00<00:00, 1.12MB/s]
tokenizer.json: 100%|███████████████████████| 466k/466k [00:00<00:00, 12.1MB/s]
special_tokens_map.json: 100%|████████████████████████| 239/239 [00:00<?, ?B/s]
Traceback (most recent call last):
  File "D:\AI\ViPE-Videos\generate_video.py", line 509, in <module>
    main()
  File "D:\AI\ViPE-Videos\generate_video.py", line 124, in main
    lyric2prompt = get_lyrtic2prompts(my_args)
  File "D:\AI\ViPE-Videos\ViPE\utils.py", line 136, in get_lyrtic2prompts
    mpnet_object = mpnet_embed_class(device='cuda', nli=True)
  File "D:\AI\ViPE-Videos\ViPE\semantic_similarity_eval.py", line 53, in __init_
_
    model.to(device)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\transformers\modeling_utils.py",
 line 1902, in to
    return super().to(*args, **kwargs)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\nn\modules\module.py", lin
e 1145, in to
    return self._apply(convert)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\nn\modules\module.py", lin
e 797, in _apply
    module._apply(fn)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\nn\modules\module.py", lin
e 797, in _apply
    module._apply(fn)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\nn\modules\module.py", lin
e 820, in _apply
    param_applied = fn(param)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\nn\modules\module.py", lin
e 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No
ne, non_blocking)
  File "D:\AI\ViPE-Videos\env\lib\site-packages\torch\cuda\__init__.py", line 23
9, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Hazel1994** [comment]
It seems like your PyTorch installation wasn't compiled with CUDA support enabled or CUDA is not properly configured. Try reinstalling  PyTorch with Cuda support and make sure your system supports CUDA.
